# ============================================================
# Linux keymaps
# ============================================================

# reload config
map ctrl+shift+comma load_config_file

# tabs
map ctrl+shift+t new_tab_with_cwd

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+4 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# OS window
map ctrl+shift+n new_os_window

# layouts
map alt+o next_layout
map alt+z toggle_layout stack

# scrollback
map ctrl+shift+f show_scrollback

# pane navigation
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# close pane/window
map ctrl+shift+w close_window

# hints
map ctrl+shift+p kitten hints --type path --program @
map ctrl+shift+h kitten hints --type hash --program @
